version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql_container
    restart: always
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
  flask_app:
    build: ./
    container_name: flask_app_container
    restart: always
    tty: true
    environment:
      - MYSQL_HOST=mysql
    ports:
      - 5000:5000
    depends_on:
      - mysql